FROM openjdk:17-jdk

RUN microdnf -y update

RUN microdnf -y install python2

RUN microdnf -y install make \
                        sudo \
                        curl \
                        file \
                        gcc \
                        gcc-c++ \
                        redhat-rpm-config \
                        git

RUN microdnf -y module enable ruby:2.7

RUN microdnf -y install ruby \
                        ruby-devel
                       
RUN gem install fastlane
