FROM openjdk:17-jdk

RUN microdnf -y update

RUN microdnf -y install python

RUN microdnf -y install make \
                        sudo \
                        curl \
                        file \
                        ssh

RUN microdnf -y install ruby2.7 \
                        ruby2.7-dev \
                        build-essential ; \
    gem install fastlane
